[package]
name = "ceros-serial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acid_io = "0.1.0"
corncobs = "0.1.1"
newlib-alloc = "0.1.0"
vexv5rt = { git = "ssh://git@github.com/Culpeper-Robotics/vexv5rt", optional = true }

[features]

# If this feature is enabled this crate can run ont eh v5 brain
v5 = ["dep:vexv5rt"]

[profile.dev]
panic = "abort"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"